# 直接启动spring-cloud-config-server-demos后，
# 可以通过http://localhost:3301/config-single-server-dev.yml 来访问本文件
data:
  env: config-eureka-dev
  user:
    username: eureka-client-user-dev
    password: 1291029102

