server:
  port: 3302

# management 是关于 actuator 相关的，接下来自动刷新配置的时候需要使用
management:
  endpoint:
    shutdown:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

# data 部分是当无法读取配置中心的配置时，使用此配置，以免项目无法启动。
data:
  env: NaN
  user:
    username: NaN
    password: NaN
